version: build{build}

install:
  - cinst elixir
  - cinst mingw
  - refreshenv

build_script:
  - mix local.hex --force
  - mix deps.get
  - mix compile
  - mix test test/uartless_test.exs

artifacts:
  - path: priv/nerves_uart.exe
